# Generated by Django 6.1.1 on 2026-09-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GDriveSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('records_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('semester', models.IntegerField(default=1)),
                ('has_practical', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='marks.academicyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='marks.department')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=150)),
                ('academic_year_str', models.CharField(db_index=True, max_length=30)),
                ('semester_num', models.IntegerField(default=1)),
                ('source_type', models.CharField(default='API', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='marks.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_university_id', models.CharField(db_index=True, max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('student_name_clean', models.CharField(db_index=True, max_length=200)),
                ('practical_mark', models.FloatField(default=0.0)),
                ('theoretical_mark', models.FloatField(default=0.0)),
                ('total_mark', models.FloatField(db_index=True)),
                ('result_status', models.CharField(max_length=30)),
                ('is_grace_eligible', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.examsession')),
            ],
            options={
                'indexes': [models.Index(fields=['student_name_clean'], name='marks_stude_student_c8a790_idx'), models.Index(fields=['student_university_id'], name='marks_stude_student_b0fa5e_idx'), models.Index(fields=['session', 'total_mark'], name='marks_stude_session_07c3ae_idx')],
            },
        ),
    ]
