# Generated by Django 6.1.1 on 2026-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_clean', models.CharField(db_index=True, max_length=200, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('primary_id', models.CharField(db_index=True, max_length=50)),
                ('all_student_ids', models.JSONField(default=list)),
                ('academic_level', models.IntegerField(default=1)),
                ('department', models.CharField(default='عام', max_length=100)),
                ('cumulative_gpa', models.FloatField(default=0.0)),
                ('passed_courses_count', models.IntegerField(default=0)),
                ('carried_courses_count', models.IntegerField(default=0)),
                ('unattempted_courses_count', models.IntegerField(default=0)),
                ('total_courses_count', models.IntegerField(default=0)),
                ('highest_mark_overall', models.FloatField(default=0.0)),
                ('highest_mark_course', models.CharField(blank=True, max_length=150)),
                ('lowest_mark_overall', models.FloatField(default=0.0)),
                ('lowest_mark_course', models.CharField(blank=True, max_length=150)),
                ('academic_status', models.CharField(default='ناجح ومترفع', max_length=100)),
                ('years_summary', models.JSONField(default=list)),
                ('courses_inverted_map', models.JSONField(default=dict)),
                ('progress_chart', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['student_name_clean'], name='marks_stude_student_0ad75a_idx'), models.Index(fields=['primary_id'], name='marks_stude_primary_9bc3f9_idx'), models.Index(fields=['cumulative_gpa'], name='marks_stude_cumulat_6a6079_idx')],
            },
        ),
    ]
