# Generated by Django 6.1.1 on 2026-10-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(db_index=True, max_length=20, unique=True)),
                ('drive_folder_id', models.CharField(max_length=200)),
                ('drive_folder_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year_label'],
            },
        ),
        migrations.CreateModel(
            name='LectureStudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField()),
                ('year_name', models.CharField(max_length=50)),
                ('drive_folder_id', models.CharField(max_length=200)),
                ('drive_folder_url', models.URLField(blank=True, max_length=500)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_years', to='marks.lectureacademicyear')),
            ],
            options={
                'ordering': ['year_number'],
                'unique_together': {('academic_year', 'year_number')},
            },
        ),
        migrations.CreateModel(
            name='LectureSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(db_index=True, max_length=200)),
                ('drive_folder_id', models.CharField(max_length=200)),
                ('drive_folder_url', models.URLField(blank=True, max_length=500)),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='marks.lecturestudyyear')),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('drive_file_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('drive_view_url', models.URLField(blank=True, max_length=500)),
                ('drive_download_url', models.URLField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('date_uploaded', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='marks.lecturesubject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
